In [27]:
import pandas as pd

In [28]:
df = pd.read_csv('/home/michel/Documentos/airflow_docker/dags_iventory_v1/data/trusted/df_dags_inventary_all.csv')
df

,ocorrencia,task,info
0,2023-11-23T18:28:13.687+0000,taskinstance.py:1083,Dependencies all met for <TaskInstance: extrai...
1,2023-11-23T18:28:13.706+0000,taskinstance.py:1083,Dependencies all met for <TaskInstance: extrai...
2,2023-11-23T18:28:13.707+0000,taskinstance.py:1279,NaN
3,2023-11-23T18:28:13.707+0000,taskinstance.py:1280,Starting attempt 1 of 2
4,2023-11-23T18:28:13.708+0000,taskinstance.py:1281,NaN
...,...,...,...
1350,2023-11-23T19:26:24.040+0000,manager.py:726,Searching for files in /opt/airflow/dags
1351,2023-11-23T19:26:24.044+0000,manager.py:729,There are 1 files in /opt/airflow/dags
1352,2023-11-23T19:26:44.165+0000,manager.py:726,Searching for files in /opt/airflow/dags
1353,2023-11-23T19:26:44.166+0000,manager.py:729,There are 1 files in /opt/airflow/dags
1354,2023-11-23T19:26:53.276+0000,manager.py:854,NaN

In [29]:
df = pd.read_csv('/home/michel/Documentos/airflow_docker/dags_iventory_v1/data/trusted/df_dags_inventary_id.csv').drop(columns='Unnamed: 0')
df

,airflow_ctx_dag_owner,airflow_ctx_dag_id,airflow_ctx_task_id,airflow_ctx_execution_date,airflow_ctx_try_number,airflow_ctx_dag_run_id
0,***,extrair_logs_***,process_logs_dag_conexao,2023-11-23T18:28:08.526678+00:00,1,manual__2023-11-23T18:28:08.526678+00:00
1,***,extrair_logs_***,process_logs_dag_conexao,2023-11-23T18:28:08.526678+00:00,1,manual__2023-11-23T18:28:08.526678+00:00
2,***,extrair_logs_***,process_logs_dag_conexao,2023-11-23T18:28:08.526678+00:00,1,manual__2023-11-23T18:28:08.526678+00:00
3,***,extrair_logs_***,process_logs_dag_conexao,2023-11-23T18:28:08.526678+00:00,1,manual__2023-11-23T18:28:08.526678+00:00
4,***,extrair_logs_***,process_logs_dag_conexao,2023-11-23T18:28:08.526678+00:00,1,manual__2023-11-23T18:28:08.526678+00:00
...,...,...,...,...,...,...
445,***,extrair_logs_***,extrair_logs_dag_conexao,2023-11-23T18:28:08.526678+00:00,3,manual__2023-11-23T18:28:08.526678+00:00
446,***,extrair_logs_***,extrair_logs_dag_conexao,2023-11-23T16:01:59.762109+00:00,7,manual__2023-11-23T16:01:59.762109+00:00
447,***,extrair_logs_***,extrair_logs_dag_conexao,2023-11-23T18:28:08.526678+00:00,2,manual__2023-11-23T18:28:08.526678+00:00
448,***,extrair_logs_***,extrair_logs_dag_conexao,2023-11-23T18:28:08.526678+00:00,1,manual__2023-11-23T18:28:08.526678+00:00
449,***,extrair_logs_***,extrair_logs_dag_conexao,2023-11-23T18:28:08.526678+00:00,3,manual__2023-11-23T18:28:08.526678+00:00